/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.kit.runner;

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner;

class TestKitRunnerTest extends Specification {

    def "execute env-var-consumer with Gradle #gradleVersion"() {
        when:
        File projectDir = new File("../env-var-consumer")

        // Run the build
        GradleRunner runner = GradleRunner.create()
            .withGradleVersion(gradleVersion)
            .withProjectDir(projectDir)
            .forwardOutput()
            .withArguments("-I", "init.gradle", "printEnvVar")
            .withEnvironment([ENV_VAR: "foo!"])
        String buildOutput = runner.build().getOutput()

        then:
        buildOutput.contains("From init script: foo!")
        buildOutput.contains("From settings script: foo!")
        buildOutput.contains("From build script: foo!")
        buildOutput.contains("From task: foo!")

        where:
        gradleVersion << ["7.5.1", "7.4.2", "6.9.2", "6.7", "5.6.4"]
    }
}
