/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.kit.runner;

import spock.lang.Specification
import org.gradle.testkit.runner.GradleRunner;

class TestKitRunnerTest extends Specification {

    def "execute env-var-consumer"() {
        when:
        File projectDir = new File("../env-var-consumer")

        // Run the build
        GradleRunner runner = GradleRunner.create()
            .withProjectDir(projectDir)
            .forwardOutput()
            .withArguments("-I", "init.gradle", "printEnvVar")
            .withEnvironment([ENV_VAR: "foo!"])
        String buildOutput = runner.build().getOutput()

        then:
        buildOutput.contains("From init script: foo!")
        buildOutput.contains("From settings script: foo!")
        buildOutput.contains("From build script: foo!")
        buildOutput.contains("From task: foo!")
    }
}
